name: Generate Weekly Research Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_notebook:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run notebook generation
      run: |
        python generate_notebook.py --repo_url "https://github.com/Cruiz102/MASK_ML" \
                                    --branch "main" \
                                    --reference_file_path "data/references.txt" \
                                    --metadata_file_path "data/metadata.txt" \
                                    --checker_iterations 2 \
                                    --output_folder "weekly_notebook_iterations"
      env:
        GH_TOKEN: ${{ secrets.OPENAI_API_KEY }}

    - name: Upload notebook iterations
      uses: actions/upload-artifact@v3
      with:
        name: notebook-iterations
        path: weekly_notebook_iterations/
